export const PAGE_FETCH = {
    REQUEST: 'PAGE_FETCH_REQUEST',
    SUCCESS: 'PAGE_FETCH_SUCCESS',
    INVALID: 'PAGE_FETCH_INVALID',
    FAILURE: 'PAGE_FETCH_FAILURE'
};
export const CONTACT_FETCH = {
    REQUEST: 'CONTACT_FETCH_REQUEST',
    SUCCESS: 'CONTACT_FETCH_SUCCESS',
    INVALID: 'CONTACT_FETCH_INVALID',
    FAILURE: 'CONTACT_FETCH_FAILURE',
    RESET: 'CONTACT_FETCH_RESET'
};

export const PLOT_FETCH = {
    REQUEST: 'PLOT_FETCH_REQUEST',
    SUCCESS: 'PLOT_FETCH_SUCCESS',
    INVALID: 'PLOT_FETCH_INVALID',
    FAILURE: 'PLOT_FETCH_FAILURE'
};

export const CREDENTIALS_FETCH = {
    REQUEST: 'CREDENTIALS_FETCH_REQUEST',
    SUCCESS: 'CREDENTIALS_FETCH_SUCCESS',
    INVALID: 'CREDENTIALS_FETCH_INVALID',
    FAILURE: 'CREDENTIALS_FETCH_FAILURE'
};

export const CREDENTIALS_LOGOUT = 'CREDENTIALS_LOGOUT';