export const PAGE_FETCH = {
    REQUEST: 'PAGE_REQUEST',
    SUCCESS: 'PAGE_SUCCESS',
    INVALID: 'PAGE_INVALID',
    FAILURE: 'PAGE_FAILURE'
};
export const CONTACT_FETCH = {
    REQUEST: 'CONTACT_REQUEST',
    SUCCESS: 'CONTACT_SUCCESS',
    INVALID: 'CONTACT_INVALID',
    FAILURE: 'CONTACT_FAILURE',
    RESET: 'CONTACT_RESET'
};

export const PLOT_FETCH = {
    REQUEST: 'PLOT_REQUEST',
    SUCCESS: 'PLOT_SUCCESS',
    INVALID: 'PLOT_INVALID',
    FAILURE: 'PLOT_FAILURE'
};

export const CREDENTIALS_FETCH = {
    REQUEST: 'CREDENTIALS_REQUEST',
    SUCCESS: 'CREDENTIALS_SUCCESS',
    INVALID: 'CREDENTIALS_INVALID',
    FAILURE: 'CREDENTIALS_FAILURE'
};

export const CREDENTIALS_LOGOUT = 'CREDENTIALS_LOGOUT';